// Add regions in select
	var regionsHR = [
		'ZAGREBAČKA',
		'KRAPINSKO-ZAGORSKA',
		'SISAČKO-MOSLAVAČKA',
		'KARLOVAČKA',
		'VARAŽDINSKA',
		'KOPRIVNIČKO-KRIŽEVAČKA',
		'BJELOVARSKO-BILOGORSKA',
		'PRIMORSKO-GORANSKA',
		'LIČKO-SENJSKA',
		'VIROVITIČKO-PODRAVSKA',
		'POŽEŠKO-SLAVONSKA',
		'BRODSKO-POSAVSKA',
		'ZADARSKA',
		'OSJEČKO-BARANJSKA',
		'ŠIBENSKO-KNINSKA',
		'VUKOVARSKO-SRIJEMSKA',
		'SPLITSKO-DALMATINSKA',
		'ISTARSKA',
		'DUBROVAČKO-NERETVANSKA',
		'MEĐIMURSKA',
		'GRAD ZAGREB',
	];
	
	var regionsCity = new Array;
	regionsCity[0] = [];
	regionsCity[1] = [
		'Dugo Selo',
		'Ivanić Grad',
		'Jastrebarsko',
		'Samobor',
		'Sveta Nedelja',
		'Sveti Ivan Zelina',
		'Velika Gorica',
		'Vrbovec',
		'Zaprešić',
		'Bedenica',
		'Bistra',
		'Brckovljani',
		'Brdovec',
		'Dubrava',
		'Dubravica',
		'Farkaševac',
		'Gradec',
		'Jakovlje',
		'Klinča Sela',
		'Kloštar Ivanić',
		'Krašić',
		'Kravarsko',
		'Križ',
		'Luka',
		'Marija Gorica',
		'Orle',
		'Pisarovina',
		'Pokupsko',
		'Preseka',
		'Pušća',
		'Rakovec',
		'Rugvica',
		'Stupnik',
		'Žumberak'
	];
	regionsCity[2] = [
		'Donja Stubica',
		'Klanjec',
		'Krapina',
		'Oroslavje',
		'Pregrada',
		'Zabok',
		'Zlatar',
		'Bedekovčina',
		'Budinščina',
		'Desinić',
		'Đurmanec',
		'Gornja Stubica',
		'Hrašćina',
		'Hum na Sutli',
		'Jesenje',
		'Konjščina',
		'Kraljevec na Sutli',
		'Krapinske Toplice',
		'Kumrovec',
		'Lobor',
		'Mače',
		'Marija Bistrica',
		'Mihovljan',
		'Novi Golubovec',
		'Petrovsko',
		'Radoboj',
		'Stubičke Toplice',
		'Sveti Križ Začretje',
		'Tuhelj',
		'Veliko Trgovišće',
		'Zagorska Sela',
		'Zlatar Bistrica',
	];
	regionsCity[3] = [
		'Glina',
		'Hrvatska Kostajnica',
		'Kutina',
		'Novska',
		'Petrinja',
		'Popovača',
		'Sisak',
		'Donji Kukuruzari',
		'Dvor',
		'Gvozd',
		'Hrvatska Dubica',
		'Jasenovac',
		'Lekenik',
		'Lipovljani',
		'Majur',
		'Martinska Ves',
		'Sunja',
		'Topusko',
		'Velika Ludina',
	];
	regionsCity[4] = [
		'Duga Resa',
		'Karlovac',
		'Ogulin',
		'Ozalj',
		'Slunj',
		'Barilović',
		'Bosiljevo',
		'Cetingrad',
		'Draganić',
		'Generalski Stol',
		'Josipdol',
		'Kamanje',
		'Krnjak',
		'Lasinja',
		'Netretić',
		'Plaški',
		'Rakovica',
		'Ribnik',
		'Saborsko',
		'Tounj',
		'Vojnić',
		'Žakanje',
	];
	regionsCity[5] = [
		'Ivanec',
		'Lepoglava',
		'Ludbreg',
		'Novi Marof',
		'Varaždin',
		'Varaždinske Toplice',
		'Bednja',
		'Beretinec',
		'Breznica',
		'Breznički Hum',
		'Cestica',
		'Donja Voća',
		'Gornji Kneginec',
		'Jalžabet',
		'Klenovnik',
		'Ljubešćica',
		'Mali Bukovec',
		'Martijanec',
		'Maruševec',
		'Petrijanec',
		'Sračinec',
		'Sveti Đurđ',
		'Sveti Ilija',
		'Trnovec Bartolovečki',
		'Veliki Bukovec',
		'Vidovec',
		'Vinica',
		'Visoko',
	];
	regionsCity[6] = [
		'Đurđevac',
		'Koprivnica',
		'Križevci',
		'Drnje',
		'Đelekovec',
		'Ferdinandovac',
		'Gola',
		'Gornja Rijeka',
		'Hlebine',
		'Kalinovac',
		'Kalnik',
		'Kloštar Podravski',
		'Koprivnički Bregi',
		'Koprivnički Ivanec',
		'Legrad',
		'Molve',
		'Novigrad Podravski',
		'Novo Virje',
		'Peteranec',
		'Podravske Sesvete',
		'Rasinja',
		'Sokolovac',
		'Sveti Ivan Žabno',
		'Sveti Petar Orehovec',
		'Virje',
	];
	regionsCity[7] = [
		'Bjelovar',
		'Čazma',
		'Daruvar',
		'Garešnica',
		'Grubišno Polje',
		'Berek',
		'Dežanovac',
		'Đulovac',
		'Hercegovac',
		'Ivanska',
		'Kapela',
		'Končanica',
		'Nova Rača',
		'Rovišće',
		'Severin',
		'Sirač',
		'Šandrovac',
		'Štefanje',
		'Velika Pisanica',
		'Velika Trnovitica',
		'Veliki Grđevac',
		'Veliko Trojstvo',
		'Zrinski Topolovac',
	];
	regionsCity[8] = [
		'Bakar',
		'Cres',
		'Crikvenica',
		'Čabar',
		'Delnice',
		'Kastav',
		'Kraljevica',
		'Krk',
		'Mali Lošinj',
		'Novi Vinodolski',
		'Opatija',
		'Rab',
		'Rijeka',
		'Vrbovsko',
		'Baška',
		'Brod Moravice',
		'Čavle',
		'Dobrinj',
		'Fužine',
		'Jelenje',
		'Klana',
		'Kostrena',
		'Lokve',
		'Lopar',
		'Lovran',
		'Malinska-Dubašnica',
		'Matulji',
		'Mošćenička Draga',
		'Mrkopalj',
		'Omišalj',
		'Punat',
		'Ravna Gora',
		'Skrad',
		'Vinodolska općina (sjedište Bribir)',
		'Viškovo',
		'Vrbnik',
	];
	regionsCity[9] = [
		'Gospić',
		'Novalja',
		'Otočac',
		'Senj',
		'Brinje',
		'Donji Lapac',
		'Karlobag',
		'Lovinac',
		'Perušić',
		'Plitvička jezera (sjedište Korenica)',
		'Udbina',
		'Vrhovine',
	];
	regionsCity[10] = [
		'Orahovica',
		'Slatina',
		'Virovitica',
		'Crnac',
		'Čačinci',
		'Čađavica',
		'Gradina',
		'Lukač',
		'Mikleuš',
		'Nova Bukovica',
		'Pitomača',
		'Sopje',
		'Suhopolje',
		'Špišić Bukovica',
		'Voćin',
		'Zdenci',
	];
	regionsCity[11] = [
		'Kutjevo',
		'Lipik',
		'Pakrac',
		'Pleternica',
		'Požega',
		'Brestovac',
		'Čaglin',
		'Jakšić',
		'Kaptol',
		'Velika',
	];
	regionsCity[12] = [
		'Nova Gradiška',
		'Slavonski Brod',
		'Bebrina',
		'Brodski Stupnik',
		'Bukovlje',
		'Cernik',
		'Davor',
		'Donji Andrijevci',
		'Dragalić',
		'Garčin',
		'Gornja Vrba',
		'Gornji Bogićevci',
		'Gundinci',
		'Klakar',
		'Nova Kapela',
		'Okučani',
		'Oprisavci',
		'Oriovac',
		'Podcrkavlje',
		'Rešetari',
		'Sibinj',
		'Sikirevci',
		'Slavonski Šamac',
		'Stara Gradiška',
		'Staro Petrovo Selo',
		'Velika Kopanica',
		'Vrbje',
		'Vrpolje',
	];
	regionsCity[13] = [
		'Benkovac',
		'Biograd na Moru',
		'Nin',
		'Obrovac',
		'Pag',
		'Zadar',
		'Bibinje',
		'Galovac',
		'Gračac',
		'Jasenice',
		'Kali',
		'Kolan',
		'Kukljica',
		'Lišane Ostrovičke',
		'Novigrad',
		'Pakoštane',
		'Pašman',
		'Polača',
		'Poličnik',
		'Posedarje',
		'Povljana',
		'Preko',
		'Privlaka',
		'Ražanac',
		'Sali',
		'Stankovci',
		'Starigrad',
		'Sukošan',
		'Sveti Filip i Jakov',
		'Škabrnja',
		'Tkon',
		'Vir',
		'Vrsi',
		'Zemunik Donji',
	];
	regionsCity[14] = [
		'Beli Manastir',
		'Belišće',
		'Donji Miholjac',
		'Đakovo',
		'Našice',
		'Osijek',
		'Valpovo',
		'Antunovac',
		'Bilje',
		'Bizovac',
		'Čeminac',
		'Čepin',
		'Darda',
		'Donja Motičina',
		'Draž',
		'Drenje',
		'Đurđenovac',
		'Erdut',
		'Ernestinovo',
		'Feričanci',
		'Gorjani',
		'Jagodnjak',
		'Kneževi Vinogradi',
		'Koška',
		'Levanjska Varoš',
		'Magadenovac',
		'Marijanci',
		'Petlovac',
		'Petrijevci',
		'Podgorač',
		'Podravska Moslavina',
		'Popovac',
		'Punitovci',
		'Satnica Đakovačka',
		'Semeljci',
		'Strizivojna',
		'Šodolovci',
		'Trnava',
		'Viljevo',
		'Viškovci',
		'Vladislavci',
		'Vuka',
	];
	regionsCity[15] = [
		'Drniš',
		'Knin',
		'Skradin',
		'Šibenik',
		'Vodice',
		'Bilice',
		'Biskupija',
		'Civljane',
		'Ervenik',
		'Kijevo',
		'Kistanje',
		'Murter-Kornati',
		'Pirovac',
		'Primošten',
		'Promina (sjedište Oklaj)',
		'Rogoznica',
		'Ružić (sjedište Gradac)',
		'Tisno',
		'Tribunj',
		'Unešić',
	];
	regionsCity[16] = [
		'Ilok',
		'Otok',
		'Vinkovci',
		'Vukovar',
		'Županja',
		'Andrijaševci',
		'Babina Greda',
		'Bogdanovci',
		'Borovo',
		'Bošnjaci',
		'Cerna',
		'Drenovci',
		'Gradište',
		'Gunja',
		'Ivankovo',
		'Jarmina',
		'Lovas',
		'Markušica',
		'Negoslavci',
		'Nijemci',
		'Nuštar',
		'Privlaka',
		'Stari Jankovci',
		'Stari Mikanovci',
		'Štitar',
		'Tompojevci',
		'Tordinci',
		'Tovarnik',
		'Trpinja',
		'Vođinci',
		'Vrbanja',
	];
	regionsCity[17] = [
		'Hvar',
		'Imotski',
		'Kaštela (sjedište Kaštel Sućurac)',
		'Komiža',
		'Makarska',
		'Omiš',
		'Sinj',
		'Solin',
		'Split',
		'Stari Grad',
		'Supetar',
		'Trilj',
		'Trogir',
		'Vis',
		'Vrgorac',
		'Vrlika',
		'Baška Voda',
		'Bol',
		'Brela',
		'Cista Provo',
		'Dicmo (sjedište Kraj)',
		'Dugi Rat',
		'Dugopolje',
		'Gradac',
		'Hrvace',
		'Jelsa',
		'Klis',
		'Lećevica',
		'Lokvičići',
		'Lovreć',
		'Marina',
		'Milna',
		'Muć',
		'Nerežišća',
		'Okrug(sjedište Okrug Gornji)',
		'Otok',
		'Podbablje (sjedište Drum)',
		'Podgora',
		'Podstrana',
		'Postira',
		'Prgomet',
		'Primorski Dolac',
		'Proložac',
		'Pučišća',
		'Runovići',
		'Seget (sjedište Seget Donji)',
		'Selca',
		'Sućuraj',
		'Sutivan',
		'Šestanovac',
		'Šolta (sjedište Grohote)',
		'Tučepi',
		'Zadvarje',
		'Zagvozd',
		'Zmijavci',
	];
	regionsCity[18] = [
		'Buje-Buie',
		'Buzet',
		'Labin',
		'Novigrad – Cittanova',
		'Pazin',
		'Poreč - Parenzo',
		'Pula - Pola',
		'Rovinj - Rovigno',
		'Umag - Umago',
		'Vodnjan - Dignano',
		'Bale - Valle',
		'Barban',
		'Brtonigla – Verteneglio',
		'Cerovlje',
		'Fažana – Fasana',
		'Funtana – Fontane',
		'Gračišće',
		'Grožnjan – Grisignana',
		'Kanfanar',
		'Karojba',
		'Kaštelir–Labinci – Castelliere-S. Domenica',
		'Kršan',
		'Lanišće',
		'Ližnjan – Lisignano',
		'Lupoglav',
		'Marčana',
		'Medulin',
		'Motovun – Montona',
		'Oprtalj – Portole',
		'Pićan',
		'Raša',
		'Sveta Nedelja',
		'Sveti Lovreč',
		'Sveti Petar u Šumi',
		'Svetvinčenat',
		'Tar-Vabriga – Torre–Abrega',
		'Tinjan',
		'Višnjan – Visignano',
		'Vižinada – Visinada',
		'Vrsar – Orsera',
		'Žminj',
	];
	regionsCity[19] = [
		'Dubrovnik',
		'Korčula',
		'Metković',
		'Opuzen',
		'Ploče',
		'Blato',
		'Dubrovačko primorje (sjedište Slano)',
		'Janjina',
		'Konavle (sjedište Cavtat)',
		'Kula Norinska',
		'Lastovo',
		'Lumbarda',
		'Mljet (sjedište Babino Polje)',
		'Orebić',
		'Pojezerje (sjedište Otrić-Seoci)',
		'Slivno (sjedište Vlaka)',
		'Smokvica',
		'Ston',
		'Trpanj',
		'Vela Luka',
		'Zažablje (sjedište Mlinište)',
		'Župa dubrovačka (sjedište Srebreno)',
	];
	regionsCity[20] = [
		'Čakovec',
		'Mursko Središće',
		'Prelog',
		'Belica',
		'Dekanovec',
		'Domašinec',
		'Donja Dubrava',
		'Donji Kraljevec',
		'Donji Vidovec',
		'Goričan',
		'Gornji Mihaljevec',
		'Kotoriba',
		'Mala Subotica',
		'Nedelišće',
		'Orehovica',
		'Podturen',
		'Pribislavec',
		'Selnica',
		'Strahoninec',
		'Sveta Marija',
		'Sveti Juraj na Bregu (sjedište Lopatinec)',
		'Sveti Martin na Muri',
		'Šenkovec',
		'Štrigova',
		'Vratišinec',
	];
	regionsCity[21] = [
		'Zagreb'
	];